version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"

  streamlit:
    build: .
    command: streamlit run streamlit_ui/ui.py
    ports:
      - "8501:8501"
    depends_on:
      - backend